# Google Cloud Buildpacks Project Descriptor
# See https://github.com/GoogleCloudPlatform/buildpacks/blob/main/README.md

# Set a schema version
schema-version = "0.2"

# List of buildpack IDs to be used in the build
# We are explicitly defining the buildpacks to use, in order.
[[build.buildpacks]]
id = "google.java.maven"

[[build.buildpacks]]
id = "google.java.runtime"

# Environment variables to be set during the build.
# This section must be an array of tables.
[[build.env]]
name = "GOOGLE_RUNTIME_VERSION"
value = "17"
