package rocks.ifa.spring.application.auth.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Standard authentication response, providing a Firebase Custom Token for client-side sign-in.")
@JsonInclude(JsonInclude.Include.NON_NULL)
public record AuthResponseDTO(
    @Schema(description = "The Firebase Custom Token generated by the server. " +
                          "The client uses this token to sign in with the Firebase SDK.")
    String customToken,

    @Schema(description = "A message providing additional context, typically for error scenarios.")
    String message
) {
}
