-- 1. User Profiles (Core Table)
CREATE TABLE IF NOT EXISTS user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL UNIQUE,
    birth_date DATE,
    gender VARCHAR(10),
    current_age INT,
    life_expectancy INT,
    marriage_year INT, -- ✅ Reverted to INT as requested
    career_insurance_type VARCHAR(50),
    biography TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
