-- 2. User Careers
CREATE TABLE IF NOT EXISTS user_careers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL UNIQUE REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    base_salary NUMERIC,
    other_allowance NUMERIC,
    labor_insurance NUMERIC,
    health_insurance NUMERIC,
    other_deduction NUMERIC,
    pension_personal_rate NUMERIC,
    pension_personal_amount NUMERIC,
    pension_employer_amount NUMERIC,
    pension_total_amount NUMERIC,
    stock_deduction NUMERIC,
    stock_company_match NUMERIC,
    dependents INT,
    monthly_net_income NUMERIC,
    annual_bonus NUMERIC,
    annual_total_income NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
