-- 3. User Labor Insurances
CREATE TABLE IF NOT EXISTS user_labor_insurances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL UNIQUE REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    expected_claim_age INT,
    average_monthly_salary NUMERIC,
    insurance_seniority INT,
    predicted_remaining_life NUMERIC,
    predicted_monthly_annuity NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
