-- 4. User Labor Pensions
CREATE TABLE IF NOT EXISTS user_labor_pensions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL UNIQUE REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    expected_retirement_age INT,
    remaining_life_at_retirement NUMERIC,
    retirement_roi NUMERIC,
    employer_contribution NUMERIC,
    employer_earnings NUMERIC,
    personal_contribution NUMERIC,
    personal_earnings NUMERIC,
    current_work_seniority NUMERIC,
    predicted_lump_sum NUMERIC,
    predicted_net_lump_sum NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
