-- 6. User Retirements
CREATE TABLE IF NOT EXISTS user_retirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL UNIQUE REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,

    -- Phase 1: Go-Go
    household_type VARCHAR(255) NOT NULL,
    housing_mode VARCHAR(255),
    housing_cost NUMERIC,
    health_tier_code VARCHAR(255),
    health_cost NUMERIC,
    active_living_code VARCHAR(255),
    active_living_cost NUMERIC,

    -- Phase 2: Slow-Go
    slow_go_start_age INT,
    defense_tier_code VARCHAR(255),
    monthly_medical_cost NUMERIC,
    critical_illness_code VARCHAR(255),
    critical_illness_reserve NUMERIC,

    -- Phase 3: No-Go
    nogo_start_age INT,
    ltc_care_mode VARCHAR(255),
    ltc_monthly_cost NUMERIC,
    ltc_monthly_supplies NUMERIC,
    ltc_subsidy NUMERIC,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
