-- 7. User Businesses
CREATE TABLE IF NOT EXISTS user_businesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    name VARCHAR(255),
    start_date DATE,
    project_years INT,
    tax_category VARCHAR(255),
    acquisition_cost NUMERIC,
    income_mode VARCHAR(255),
    total_accumulated_income NUMERIC,
    monthly_income NUMERIC,
    monthly_cost NUMERIC,
    loan_amount NUMERIC,
    loan_interest_rate NUMERIC,
    roi VARCHAR(255),
    irr VARCHAR(255),
    group_id INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
