-- 8. User Credit Cards
CREATE TABLE IF NOT EXISTS user_credit_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    name VARCHAR(255),
    deduction_account VARCHAR(255),
    usage_type VARCHAR(255),
    storage_location VARCHAR(255),
    average_monthly_expense NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
