-- 9. User Portfolios
CREATE TABLE IF NOT EXISTS user_portfolios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    country_code VARCHAR(255),
    currency VARCHAR(255),
    exchange_rate NUMERIC,
    market_value NUMERIC,
    realized_pnl NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
