-- 10. User Real Estates
CREATE TABLE IF NOT EXISTS user_real_estates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    name VARCHAR(255),
    age INT,
    size NUMERIC,
    price_per_ping NUMERIC,
    total_price NUMERIC,
    assessed_value NUMERIC,
    holding_tax_rate NUMERIC,
    actual_holding_cost NUMERIC,
    loan_amount NUMERIC,
    interest_rate NUMERIC,
    usage_type VARCHAR(255),
    monthly_rent NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
