CREATE TABLE client_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_firebase_uid VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    birth_date DATE,
    gender VARCHAR(255),
    current_age INTEGER,
    life_expectancy INTEGER,
    marriage_year INTEGER,
    career_insurance_type VARCHAR(255),
    biography TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,

    -- To ensure that one agent cannot have multiple clients with the same email
    UNIQUE (agent_firebase_uid, email)
);
